//
//  JournalView.swift
//  Harmonia
//
//  Created by Kayla Ann Newton on 7/19/23.
//

import SwiftUI

struct JournalView: View {
    var body: some View {
        ScrollView {
            VStack {
                Text("jdfkajdflskafjdskfjdskfdsjkfdsjfkldsfkjfafjdsklfjkskjkfjskfsjdklfjsfksdjfsjdklfjlsjfldsjfkldsjfkldsjfklsjdkfljslfjklsajflksdjflkdsjfkldsjfjsalfhwfhocrucoqwieuroweroweurow3uroiwejrlqyruiowhejkfrhawliyw4quirhfsjkhroiqwuyreulkjfhjkewy5iuwehfjkshtipuethuahgterqlitypuierht;rahfjksdhtpirytuirhfkjasdyuiryrtuihvjksdhfuayturhgurjegnjfnjkdjngjahrgiurjdfkajdflskafjdskfjdskfdsjkfdsjfkldsfkjfafjdsklfjkskjkfjskfsjdklfjsfksdjfsjdklfjlsjfldsjfkldsjfkldsjfklsjdkfljslfjklsajflksdjflkdsjfkldsjfjsalfhwfhocrucoqwieuroweroweurow3uroiwejrlqyruiowhejkfrhawliyjdfkajdflskafjdskfjdskfdsjkfdsjfkldsfkjfafjdsklfjkskjkfjskfsjdklfjsfksdjfsjdklfjlsjfldsjfkldsjfkldsjfklsjdkfljslfjklsajflksdjflkdsjfkldsjfjsalfhwfhocrucoqwieuroweroweurow3uroiwejrlqyruiowhejkfrhawliyw4quirhfsjkhroiqwuyreulkjfhjkewy5iuwehfjkshtipuethuahgterqlitypuierht;rahfjksdhtpirytuirhfkjasdyuiryrtuihvjksdhfuayturhgurjegnjfnjkdjngjahrgiurjdfkajdflskafjdskfjdskfdsjkfdsjfkldsfkjfafjdsklfjkskjkfjskfsjdklfjsfksdjfsjdklfjlsjfldsjfkldsjfkldsjfklsjdkfljslfjklsajflksdjflkdsjfkldsjfjsalfhwfhocrucoqwieuroweroweurow3uroiwejrlqyruiowhejkfrhawliyjdfkajdflskafjdskfjdskfdsjkfdsjfkldsfkjfafjdsklfjkskjkfjskfsjdklfjsfksdjfsjdklfjlsjfldsjfkldsjfkldsjfklsjdkfljslfjklsajflksdjflkdsjfkldsjfjsalfhwfhocrucoqwieuroweroweurow3uroiwejrlqyruiowhejkfrhawliyw4quirhfsjkhroiqwuyreulkjfhjkewy5iuwehfjkshtipuethuahgterqlitypuierht;rahfjksdhtpirytuirhfkjasdyuiryrtuihvjksdhfuayturhgurjegnjfnjkdjngjahrgiurjdfkajdflskafjdskfjdskfdsjkfdsjfkldsfkjfafjdsklfjkskjkfjskfsjdklfjsfksdjfsjdklfjlsjfldsjfkldsjfkldsjfklsjdkfljslfjklsajflksdjflkdsjfkldsjfjsalfhwfhocrucoqwieuroweroweurow3uroiwejrlqyruiowhejkfrhawliy")
                Text("jdfkajdflskafjdskfjdskfdsjkfdsjfkldsfkjfafjdsklfjkskjkfjskfsjdklfjsfksdjfsjdklfjlsjfldsjfkldsjfkldsjfklsjdkfljslfjklsajflksdjflkdsjfkldsjfjsalfhwfhocrucoqwieuroweroweurow3uroiwejrlqyruiowhejkfrhawliyw4quirhfsjkhroiqwuyreulkjfhjkewy5iuwehfjkshtipuethuahgterqlitypuierht;rahfjksdhtpirytuirhfkjasdyuiryrtuihvjksdhfuayturhgurjegnjfnjkdjngjahrgiurjdfkajdflskafjdskfjdskfdsjkfdsjfkldsfkjfafjdsklfjkskjkfjskfsjdklfjsfksdjfsjdklfjlsjfldsjfkldsjfkldsjfklsjdkfljslfjklsajflksdjflkdsjfkldsjfjsalfhwfhocrucoqwieuroweroweurow3uroiwejrlqyruiowhejkfrhawliyw4quirhfsjkhroiqwuyreulkjfhjkewy5iuwehfjkshtipuethuahgterqlity")
            }
        } .padding()
    }
}

struct JournalView_Previews: PreviewProvider {
    static var previews: some View {
        JournalView()
    }
}

